#!/usr/bin/env bash

function opm()
{
    if [[ -d "opm" ]]; then
        printf "opm found"
    else 
        git clone https://github.com/Neotoxic-off/opm
    fi
    cd opm
    rm packages.opm
    cp ../packages.opm .
    ./opm
}

opm
